// INTEGRATION: MockDeviceAdapter (DESIGN.md §5.3 · DESIGN_WINDOWS.md §1 — the no-hardware rig)
// IN:  cortex/fixtures/frame-NN-<class>.jpg (generated by cortex/fixtures/generate.ts):
//      nothing x3 -> banner x3 -> nothing x2 -> document x2.
// OUT: the same GatewayEvents callbacks a real device produces
//      (onDeviceSessionStart -> onFrame x10 -> optional onPhoto) and it IS a DeviceChannel,
//      so SessionOrchestrator renders into it exactly as into glasses. Every
//      CortexToDeviceMsg received is logged (and kept in `sent` for assertions).
// WIRE: const mock = new MockDeviceAdapter({ events: orchestrator });
//       await mock.start();   // in cortex/src/index.ts behind MOCK_DEVICE=1, or in tests
//
// This is what makes the whole pipeline testable from hour 3 with zero hardware, and what
// the outage drill (DESIGN.md §8) runs against.

import { readFile, readdir } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import type { CortexToDeviceMsg, DeviceType } from "@wingman/shared";
import { FRAME_INTERVAL_MS } from "@wingman/shared";
import type { DeviceChannel, GatewayEvents } from "../interfaces.js";

export interface MockLogger {
  info(msg: string, meta?: Record<string, unknown>): void;
}

const consoleLogger: MockLogger = {
  // eslint-disable-next-line no-console
  info: (msg, meta) => console.log(`[mock-device] ${msg}`, meta ?? ""),
};

export interface MockDeviceAdapterDeps {
  events: GatewayEvents;
  deviceId?: string;
  deviceType?: DeviceType;
  /** Defaults to cortex/fixtures. */
  fixturesDir?: string;
  /** Replay cadence; defaults to the device sampling cadence (Appendix D). */
  intervalMs?: number;
  /** Replay the walk forever instead of stopping after the last frame. */
  loop?: boolean;
  /** Answer capture_photo with the last `document` fixture (default true). */
  respondToCapturePhoto?: boolean;
  logger?: MockLogger;
}

export interface MockFixture {
  name: string;
  cls: "nothing" | "banner" | "document";
  jpeg: Buffer;
}

export class MockDeviceAdapter implements DeviceChannel {
  readonly deviceId: string;
  readonly deviceType: DeviceType;
  /** Every CortexToDeviceMsg this fake device received, in order (test affordance). */
  readonly sent: CortexToDeviceMsg[] = [];

  #fixtures: MockFixture[] = [];
  #timer: ReturnType<typeof setInterval> | null = null;
  #cursor = 0;
  #seq = 0;
  #closed = false;

  constructor(private readonly deps: MockDeviceAdapterDeps) {
    this.deviceId = deps.deviceId ?? "mock-device";
    this.deviceType = deps.deviceType ?? "phone_web";
  }

  get fixtures(): readonly MockFixture[] {
    return this.#fixtures;
  }

  /** Load the fixture walk and begin replaying it as session frames. */
  async start(): Promise<void> {
    this.#closed = false;
    this.#cursor = 0;
    this.#fixtures = await this.#loadFixtures();
    this.#log("session_start", { frames: this.#fixtures.length });
    this.deps.events.onDeviceSessionStart(this);
    const interval = this.deps.intervalMs ?? FRAME_INTERVAL_MS;
    this.#timer = setInterval(() => this.#tick(), interval);
  }

  /** Stop replaying and report a device-side session_stop. */
  stop(): void {
    this.#clearTimer();
    this.#log("session_stop");
    this.deps.events.onDeviceSessionStop(this.deviceId);
  }

  // --- DeviceChannel -------------------------------------------------------

  send(msg: CortexToDeviceMsg): void {
    this.sent.push(msg);
    this.#log(`<- ${msg.type}`, summarize(msg));
    if (
      msg.type === "capture_photo" &&
      this.deps.respondToCapturePhoto !== false &&
      !this.#closed
    ) {
      const doc = [...this.#fixtures].reverse().find((f) => f.cls === "document");
      if (doc) {
        this.#log("-> photo", { reqId: msg.reqId, fixture: doc.name });
        this.deps.events.onPhoto(this.deviceId, msg.reqId, doc.jpeg);
      } else {
        this.deps.events.onPhotoError(this.deviceId, msg.reqId, "no_document_fixture");
      }
    }
  }

  close(): void {
    if (this.#closed) return;
    this.#closed = true;
    this.#clearTimer();
    this.#log("closed");
    this.deps.events.onDisconnect(this.deviceId);
  }

  // --- internals -----------------------------------------------------------

  #tick(): void {
    if (this.#closed) return;
    if (this.#cursor >= this.#fixtures.length) {
      if (this.deps.loop) {
        this.#cursor = 0;
      } else {
        this.#clearTimer();
        this.#log("replay complete", { frames: this.#seq });
        return;
      }
    }
    const fixture = this.#fixtures[this.#cursor++]!;
    const seq = ++this.#seq;
    this.#log(`-> frame ${seq}`, { fixture: fixture.name, expected: fixture.cls });
    this.deps.events.onFrame(this.deviceId, seq, fixture.jpeg);
  }

  #clearTimer(): void {
    if (this.#timer) {
      clearInterval(this.#timer);
      this.#timer = null;
    }
  }

  #log(msg: string, meta?: Record<string, unknown>): void {
    (this.deps.logger ?? consoleLogger).info(msg, meta);
  }

  async #loadFixtures(): Promise<MockFixture[]> {
    const dir = this.deps.fixturesDir ?? defaultFixturesDir();
    const names = (await readdir(dir))
      .filter((n) => n.endsWith(".jpg") || n.endsWith(".jpeg"))
      .sort();
    if (names.length === 0) {
      throw new Error(
        `MockDeviceAdapter: no fixture JPEGs in ${dir} — run \`pnpm -F @wingman/cortex fixtures\``,
      );
    }
    return Promise.all(
      names.map(async (name) => ({
        name,
        cls: classOf(name),
        jpeg: await readFile(`${dir}/${name}`),
      })),
    );
  }
}

function defaultFixturesDir(): string {
  return fileURLToPath(new URL("../../fixtures/", import.meta.url));
}

/** Filename carries the expected gate class — replay ordering + test assertions. */
function classOf(name: string): "nothing" | "banner" | "document" {
  if (name.includes("banner")) return "banner";
  if (name.includes("document")) return "document";
  return "nothing";
}

function summarize(msg: CortexToDeviceMsg): Record<string, unknown> {
  switch (msg.type) {
    case "armed":
      return { sessionId: msg.sessionId, config: msg.config };
    case "capture_photo":
      return { reqId: msg.reqId, quality: msg.quality };
    case "render":
      return {
        cardId: msg.card.cardId,
        seq: msg.card.seq,
        kind: msg.card.kind,
        title: msg.card.title,
        page: msg.card.page,
        footer: msg.card.footer,
        lines: msg.card.lines,
      };
    case "session_end":
      return { reason: msg.reason };
    case "error":
      return { code: msg.code, message: msg.message };
  }
}
